// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChMVkzqCoYJ8IEJuuMuWvJABj9RgesXvY',
    appId: '1:779298287833:android:b0d48bf3ed0f6c5c860ec8',
    messagingSenderId: '779298287833',
    projectId: 'lost-and-found-4456a',
    storageBucket: 'lost-and-found-4456a.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChMVkzqCoYJ8IEJuuMuWvJABj9RgesXvY',
    appId: '1:779298287833:web:b0d48bf3ed0f6c5cweb01',
    messagingSenderId: '779298287833',
    projectId: 'lost-and-found-4456a',
    authDomain: 'lost-and-found-4456a.firebaseapp.com',
    storageBucket: 'lost-and-found-4456a.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChMVkzqCoYJ8IEJuuMuWvJABj9RgesXvY',
    appId: '1:779298287833:ios:b0d48bf3ed0f6c5cios01',
    messagingSenderId: '779298287833',
    projectId: 'lost-and-found-4456a',
    storageBucket: 'lost-and-found-4456a.firebasestorage.app',
    iosBundleId: 'com.example.flutterLostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChMVkzqCoYJ8IEJuuMuWvJABj9RgesXvY',
    appId: '1:779298287833:ios:b0d48bf3ed0f6c5cios01',
    messagingSenderId: '779298287833',
    projectId: 'lost-and-found-4456a',
    storageBucket: 'lost-and-found-4456a.firebasestorage.app',
    iosBundleId: 'com.example.flutterLostAndFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChMVkzqCoYJ8IEJuuMuWvJABj9RgesXvY',
    appId: '1:779298287833:web:b0d48bf3ed0f6c5cweb01',
    messagingSenderId: '779298287833',
    projectId: 'lost-and-found-4456a',
    authDomain: 'lost-and-found-4456a.firebaseapp.com',
    storageBucket: 'lost-and-found-4456a.firebasestorage.app',
  );
}
