[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    auth: Tests related to authentication and user login
    rating: Tests related to rating and review submission
